### ISSUE TITLE
migrate to localStorageCapacityIsolation kubelet option from feature gate

### ISSUE THREAD

**Issue by BenTheElder** [rootless-containers/usernetes#264]
The LocalStorageCapacityIsolation feature will be GA in v1.25.0 and thus there will be no feature gate, but for rootless users like this I've requested a kubelet config option that will be available in v1.25.0 thanks to `@jinxu97`.  You can set `localStorageCapacityIsolation: false` in the kubelet config instead of disabling the feature gate when Kubernetes v1.25.0 is out.

I've identified this project as using the feature gate, so this issue is a friendly heads up about the coming removal and replacement 😅 

see: https://github.com/kubernetes/kubernetes/pull/111513, https://github.com/kubernetes/enhancements/issues/361, coming in Kubernetes v1.25.0

**Comment by AkihiroSuda** [comment]
Thank your for notification, we have been already setting `LocalStorageCapacityIsolation: false`

https://github.com/rootless-containers/usernetes/blob/d0d9886d849a4898760afdb46299088bdc05e980/boot/kubelet.sh#L23

Since Apr 2020 🤔 https://github.com/rootless-containers/usernetes/commit/2960d4e17ba0bae1c174511a6d2f5f0a91af2be3

**Comment by AkihiroSuda** [comment]
Thanks, opened PR
- https://github.com/rootless-containers/usernetes/pull/265
